# Generated by Django 5.2.7 on 2025-10-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
