# Generated by Django 5.2.7 on 2025-10-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_conversation_options_ragcollection_ragdocument'),
    ]

    operations = [
    ]
