# Generated by Django 5.2.7 on 2025-10-30 04:26

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_auto_20251021_1014"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ragdocument",
            name="document_name",
        ),
        migrations.AddField(
            model_name="ragdocument",
            name="original_document_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="ragdocument",
            name="unique_document_name",
            field=models.CharField(default="-", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ragdocument",
            name="document_path",
            field=models.FileField(
                upload_to=chat.models.RAGDocument._upload_path_filename
            ),
        ),
    ]
