# Generated by Django 5.2.7 on 2025-11-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_remove_ragdocument_document_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ragcollection",
            name="vector_collection_name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
    ]
