# Generated by Django 5.2.7 on 2025-11-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_ragcollection_vector_collection_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ragcollection",
            name="vector_collection_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
