# Generated by Django 5.2.7 on 2025-12-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
